App/Models/HotelViewModel.cs
using App.Models.Utils;
using Domain.Entity;
using System.ComponentModel.DataAnnotations;

namespace App.Models
{
    public class HotelViewModel : BaseViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public decimal Price { get; set; }
        public string Location { get; set; }
        public byte Rating { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ValidFrom { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ValidUntil { get; set; }
        public int AvailableSpots { get; set; }

        public string Image { get; set; }
        public bool Active { get; set; } = true;
        public Guid CreatedById { get; set; }
        public User CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public List<Hotel> Itens { get; set; } = new List<Hotel>();
    }
}

App/Controllers/HotelController.cs
using App.Models;
using AutoMapper;
using Domain.Entity;
using Domain.Resource;
using Domain.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace Web.Controllers
{
    public class HotelController : Controller
    {
        private readonly IHotelService _service;
        private readonly IStringLocalizer<SharedResources> _localizer;
        private readonly IMapper _mapper;

        public HotelController(IHotelService service, IStringLocalizer<SharedResources> localizer, IMapper mapper)
        {
            _service = service;
            _localizer = localizer;
            _mapper = mapper;
        }

        [Authorize(Roles = "ADM")]
        public async Task<IActionResult> Index(HotelViewModel model)
        {
            if (model == null)
                model = new HotelViewModel();
            try
            {
                model.Total = await _service.Count(_mapper.Map<Hotel>(model));
                model.Itens = await _service.Get(_mapper.Map<Hotel>(model), model.Skip, model.Take);
            }
            catch (Exception ex)
            {
                TempData["ErroMessage"] = ex.Message;
            }
            return View(model);
        }

        public async Task<IActionResult> Search()
        {
            var model = new HotelSearchViewModel();
            model.Itens = await _service.Get(new Hotel(), 0, 30);
            return View(model);
        }

        [Authorize(Roles = "ADM")]
        public IActionResult Create()
        {
            return View(new HotelViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "ADM")]
        public async Task<IActionResult> Create(HotelViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Id = await _service.Insert(_mapper.Map<Hotel>(model));
                    TempData["SucessMessage"] = _localizer["Record saved successfully."];
                }
                else
                    throw new ArgumentException(_localizer["Invalid data."]);
            }
            catch (Exception ex)
            {
                TempData["ErroMessage"] = ex.Message;
            }

            return RedirectToAction("Edit", new { codigo = model.Id });
        }

        [Authorize(Roles = "ADM")]
        public async Task<IActionResult> Edit(Guid id)
        {
            HotelViewModel model = new HotelViewModel();

            try
            {
                var item = await _service.Get(id);
                if (item == null)
                    throw new ArgumentException(_localizer["Record not found"]);

                model = _mapper.Map<HotelViewModel>(item);
            }
            catch (Exception ex)
            {
                TempData["ErroMessage"] = ex.Message;
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "ADM")]
        public async Task<IActionResult> Edit(HotelViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.Update(_mapper.Map<Hotel>(model));
                    TempData["SucessMessage"] = _localizer["Record saved successfully."];
                }
                else
                    throw new ArgumentException(_localizer["Invalid data."]);
            }
            catch (Exception ex)
            {
                TempData["ErroMessage"] = ex.Message;
            }

            return RedirectToAction("Edit", new { id = model.Id });
        }
    }
}

App/Views/Hotel/Create.cshtml
@{
	ViewData["Title"] = "Create Hotel";
}

@model HotelViewModel;

<!-- Breadcrumb -->
<div class="breadcrumb-bar breadcrumb-bg-04 text-center">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12">
				<h2 class="breadcrumb-title mb-2">@Localizer["Add Hotel"]</h2>
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb justify-content-center mb-0">
						<li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")"><i class="isax isax-home5"></i></a></li>
						<li class="breadcrumb-item active" aria-current="page">@Localizer["Add Hotel"]</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>
<!-- /Breadcrumb -->
<!-- Page Wrapper -->
<div class="content">
	<div class="container">
		@* <div class="place-nav">
			<ul class="nav" role="tablist">
				<li>
					<a href="javascript:void(0);" class="nav-link active" data-bs-toggle="tab" data-bs-target="#add_hotel" aria-selected="true" role="tab">
						Add New Hotel
					</a>
				</li>
				<li>
					<a href="javascript:void(0);" class="nav-link" data-bs-toggle="tab" data-bs-target="#add_room" aria-selected="false" role="tab" tabindex="-1">
						Add New Room
					</a>
				</li>
			</ul>
		</div> *@
		<div class="tab-content">

			<!-- Add Hotel -->
			<div class="tab-pane fade active show" id="add_hotel" role="tabpanel">
				<div class="row">
					<div class="col-lg-3 theiaStickySidebar">
						<div class="card border-0 mb-4 mb-lg-0">
							<div class="card-body">
								<div>
									<h5 class="mb-3">@Localizer["Add Hotel"]</h5>
									<ul class="add-tab-list">
										<li><a href="#basic_info" class="active">@Localizer["Basic Info"]</a></li>
										<li><a href="#location">@Localizer["Locations"]</a></li>
										@* <li><a href="#highlights">@Localizer["Highlights"]</a></li>
										<li><a href="#room_types">@Localizer["Room Types"]</a></li>
										<li><a href="#popular_amenities">@Localizer["Popular Amenities"]</a></li>
										<li><a href="#faq">@Localizer["FAQ"]</a></li> *@
										@* <li><a href="#gallery">@Localizer["Gallery"]</a></li> *@
										<li><a href="#description">@Localizer["Description"]</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						<form method="post" asp-controller="Hotel" asp-action="Create">

							@await Html.PartialAsync("_Form", Model)

							<div class="d-flex align-items-center justify-content-center">
								<a href="@Url.Action("Edit", "Hotel", new { id = Model.Id })" class="btn btn-light me-2">@Localizer["Reset"]</a>
								<button type="submit" class="btn btn-primary">@Localizer["Save"]</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /Add Hotel -->
			<!-- Add Room -->
@* 			<div class="tab-pane fade" id="add_room" role="tabpanel">
				<div class="row">
					<div class="col-lg-3 theiaStickySidebar">
						<div class="card border-0">
							<div class="card-body">
								<div>
									<h5 class="mb-3">Add Room</h5>
									<ul class="add-tab-list">
										<li><a href="#basic_info_2" class="active">Basic Info</a></li>
										<li><a href="#description_2">Description</a></li>
										<li><a href="#specification">Specifications</a></li>
										<li><a href="#services">Services</a></li>
										<li><a href="#accssibilty">Accessibility</a></li>
										<li><a href="#popular_amenities_2">Amenities</a></li>
										<li><a href="#gallery_2">Gallery</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						<form method="post" asp-controller="Hotel" asp-action="Create">

							@await Html.PartialAsync("_Form", Model)

							<div class="d-flex align-items-center justify-content-center">
								<a href="@Url.Action("Edit", "Hotel", new { id = Model.Id })" class="btn btn-light me-2">@Localizer["Reset"]</a>
								<button type="submit" class="btn btn-primary">@Localizer["Save"]</button>
							</div>
						</form>
					</div>
				</div>
			</div> *@
			<!-- /Add Room -->

		</div>
	</div>
</div>
<!-- /Page Wrapper -->

App/Views/Hotel/Edit.cshtml
@{
	ViewData["Title"] = "Edit Hotel";
}

@model HotelViewModel;

<!-- Breadcrumb -->
<div class="breadcrumb-bar breadcrumb-bg-04 text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-12">
                <h2 class="breadcrumb-title mb-2">@Localizer["Edit Hotel"]</h2>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center mb-0">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")"><i class="isax isax-home5"></i></a></li>
                        <li class="breadcrumb-item active" aria-current="page">@Localizer["Edit Hotel"]</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- /Breadcrumb -->
<!-- Page Wrapper -->
<div class="content">
    <div class="container">
        @* <div class="place-nav">
            <ul class="nav" role="tablist">
                <li>
                    <a href="javascript:void(0);" class="nav-link active" data-bs-toggle="tab" data-bs-target="#add_hotel" aria-selected="true" role="tab">
                        Edit Hotel
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" class="nav-link" data-bs-toggle="tab" data-bs-target="#add_room" aria-selected="false" role="tab" tabindex="-1">
                        Edit Room
                    </a>
                </li>
            </ul>
        </div> *@
        <div class="tab-content">
            <div class="tab-pane fade active show" id="add_hotel" role="tabpanel">
                <div class="row">
                    <div class="col-lg-3 theiaStickySidebar">
                        <div class="card border-0 mb-4 mb-lg-0">
                            <div class="card-body">
                                <div>
                                    <h5 class="mb-3">@Localizer["Edit Hotel"]</h5>
                                    <ul class="add-tab-list">
                                        <li><a href="#basic_info" class="active">@Localizer["Basic Info"]</a></li>
                                        <li><a href="#location">@Localizer["Locations"]</a></li>
                                        @* <li><a href="#highlights">@Localizer["Highlights"]</a></li> *@
                                        @* <li><a href="#room_types">@Localizer["Room Types"]</a></li> *@
                                        @* <li><a href="#popular_amenities">@Localizer["Popular Amenities"]</a></li> *@
                                        @* <li><a href="#faq">@Localizer["FAQ"]</a></li> *@
                                        @* <li><a href="#gallery">@Localizer["Gallery"]</a></li> *@
                                        <li><a href="#description">@Localizer["Description"]</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <form method="post" asp-controller="Hotel" asp-action="Edit">
                            
                            @await Html.PartialAsync("_Form", Model)

                            <div class="d-flex align-items-center justify-content-center">
                                <button type="button" class="btn btn-light me-2">@Localizer["Reset"]</button>
                                <button type="submit" class="btn btn-primary">@Localizer["Save"]</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            @* <div class="tab-pane fade" id="add_room" role="tabpanel">
                <div class="row">
                    <div class="col-lg-3 theiaStickySidebar">
                        <div class="card border-0">
                            <div class="card-body">
                                <div>
                                    <h5 class="mb-3">Edit Room</h5>
                                    <ul class="add-tab-list">
                                        <li><a href="#basic_info_2" class="active">Basic Info</a></li>
                                        <li><a href="#description_2">Description</a></li>
                                        <li><a href="#specification">Specifications</a></li>
                                        <li><a href="#services">Services</a></li>
                                        <li><a href="#accssibilty">Accessibility</a></li>
                                        <li><a href="#popular_amenities_2">Amenities</a></li>
                                        <li><a href="#gallery_2">Gallery</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <form method="post" asp-controller="Hotel" asp-action="Create">

                            @await Html.PartialAsync("_Form", Model)

                            <div class="d-flex align-items-center justify-content-center">
                                <a href="@Url.Action("Create", "Hotel")" class="btn btn-light me-2">@Localizer["Reset"]</a>
                                <button type="submit" class="btn btn-primary">@Localizer["Save"]</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> *@
        </div>
    </div>
</div>
<!-- /Page Wrapper -->

App/Views/Hotel/Index.cshtml
@{
	ViewData["Title"] = "Hotel";
}

@model HotelViewModel;

<!-- Breadcrumb -->
<div class="breadcrumb-bar breadcrumb-bg-04 text-center">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12">
				<h2 class="breadcrumb-title mb-2">@Localizer["Hotel List"]</h2>
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb justify-content-center mb-0">
						<li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")"><i class="isax isax-home5"></i></a></li>
						<li class="breadcrumb-item active" aria-current="page">@Localizer["Hotel List"]</li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
</div>
<!-- /Breadcrumb -->
<!-- Page Wrapper -->
<div class="content">
	<div class="container">

		<div class="row">

			<div class="col-xl-12 col-lg-12">
				<!-- Booking Header -->
				<div class="card booking-header border-0">
					<div class="card-body header-content d-flex align-items-center justify-content-between flex-wrap ">
						<div>
							<h6 class="mb-1">Hotel List</h6>
							<p class="fs-14 text-gray-6 fw-normal ">Total : @Model.Total</p>
						</div>
						<div class="d-flex align-items-center flex-wrap">
							<button onclick="window.location.href='@Url.Action("Create", "Hotel")'" class="btn btn-primary btn-sm add-highlight">
								<i class="isax isax-add-circle me-1"></i>@Localizer["Add New"]
							</button>
						</div>
					</div>

				</div>
				<!-- /Booking Header -->
				<!-- Hotel-Booking List -->
				<div class="card hotel-list">
					<div class="card-body p-0">
						@*                         <div class="list-header d-flex align-items-center justify-content-between flex-wrap">
                            <div class="d-flex align-items-center flex-wrap">
                                <div class="input-icon-start  me-2 position-relative">
                                    <span class="icon-addon">
                                        <i class="isax isax-search-normal-1 fs-14"></i>
                                    </span>
                                    <input type="text" class="form-control" placeholder="Search">
                                </div>
                                <div class="dropdown me-3">
                                    <a href="javascript:void(0);" class="dropdown-toggle text-gray-6 btn  rounded border d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false">
                                        Room Type
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end p-3">
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item rounded-1">Single Room</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item rounded-1">Double Room</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item rounded-1">Twin Room</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="dropdown me-3">
                                    <a href="javascript:void(0);" class="dropdown-toggle text-gray-6 btn  rounded border d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false">
                                        Status
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end p-3">
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item rounded-1">Upcoming</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item rounded-1">Cancelled</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0);" class="dropdown-item rounded-1">Completed</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="d-flex align-items-center sort-by">
                                    <span class="fs-14 text-gray-9 fw-medium">Sort By :</span>
                                    <div class="dropdown">
                                        <a href="javascript:void(0);" class="dropdown-toggle text-gray-6 btn rounded d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false">
                                            Recommended
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end p-3">
                                            <li>
                                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Recently Added</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Ascending</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Desending</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Last Month</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0);" class="dropdown-item rounded-1">Last 7 Days</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                            </div>
                        </div>
 *@
						<!-- Hotel List -->
						<div class="custom-datatable-filter table-responsive">
							<table class="table datatable">
								<thead class="thead-light">
									<tr>
										<th>@Localizer["ID"]</th>
										<th>@Localizer["Hotel"]</th>
										<th>@Localizer["Created By"]</th>
										<th>@Localizer["Room & Guest"]</th>
										<th>@Localizer["Location"]</th>
										<th>@Localizer["Pricing"]</th>
										<th>@Localizer["Validity"]</th>
										<th>@Localizer["Status"]</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									@foreach (var item in Model.Itens)
									{
										<tr>
											<td><a href="javascript:void(0);" class="link-primary fw-medium" data-bs-toggle="modal" data-bs-target="#upcoming">#@item.Id</a></td>
											<td>
												<div>
													<p class="text-dark mb-0 fw-medium fs-14"><a href="javascript:void(0);">@item.Name</a></p>
													<span class="fs-14 fw-normal text-gray-6">@item.Location</span>
												</div>
											</td>
											<td>
												<h6 class="fs-14 mb-1">@item.CreatedById</h6>
												<span class="fs-14 fw-normal text-gray-6">@item.CreatedOn.ToShortDateString()</span>
											</td>
											<td>
												<h6 class="fs-14 mb-1">@item.Type</h6>
												<span class="fs-14 fw-normal text-gray-6">@item.AvailableSpots @Localizer["Spots"]</span>
											</td>
											<td>@item.Location</td>
											<td>$@item.Price</td>
											<td>@item.ValidFrom.ToShortDateString() - @item.ValidUntil.ToShortDateString()</td>
											<td>
												<span class="badge badge-info rounded-pill d-inline-flex align-items-center fs-10"><i class="fa-solid fa-circle fs-5 me-1"></i>@(item.Active ? @Localizer["Active"] : @Localizer["Inactive"])</span>
											</td>
											<td>
												<div class="d-flex align-items-center">
													<a href="@Url.Action("Edit", "Hotel", new { id = @item.Id })"><i class="isax isax-edit-2"></i></a>
												</div>
											</td>
										</tr>
									}
								</tbody>
							</table>
						</div>
						<!-- /Hotel List -->

					</div>
				</div>
				<!-- /Hotel-Booking List -->
				<!-- Pagination -->
				<div class="table-paginate d-flex justify-content-between align-items-center flex-wrap row-gap-3">
@* 					<div class="value d-flex align-items-center">
						<span>Show</span>
						<select>
							<option>5</option>
							<option>10</option>
							<option>20</option>
						</select>
						<span>entries</span>
					</div> *@
					<div class="d-flex align-items-center justify-content-center">
						<a href="javascript:void(0);"><span class="me-3"><i class="isax isax-arrow-left-2"></i></span></a>
						<nav aria-label="Page navigation">
							<ul class="paginations d-flex justify-content-center align-items-center">
								<li class="page-item me-2"><a class="page-link-1 active d-flex justify-content-center align-items-center " href="javascript:void(0);">1</a></li>
								<li class="page-item me-2"><a class="page-link-1 d-flex justify-content-center align-items-center" href="javascript:void(0);">2</a></li>
								<li class="page-item "><a class="page-link-1 d-flex justify-content-center align-items-center" href="javascript:void(0);">3</a></li>
							</ul>
						</nav>
						<a href="javascript:void(0);"><span class="ms-3"><i class="isax isax-arrow-right-3"></i></span></a>
					</div>
				</div>
				<!-- /Pagination -->
			</div>
		</div>
	</div>
</div>
<!-- /Page Wrapper -->